name: Terraform CI

on:
    push:
        branches:
            - master

permissions:
    contents: read

jobs:
    terraform:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Checkout the code
            - name: Checkout code
              uses: actions/checkout@v3

            # Step 2: Set AWS credentials from repo secrets
            - name: Set AWS Credentials
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: |
                  aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws configure set region ap-southeast-1

            # Step 3: Set up Terraform
            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: 1.9.7

            # Step 4: Install Checkov
            - name: Install Checkov
              run: |
                  pip install checkov

            # Step 5: Run Checkov for Terraform static analysis
            - name: Run Checkov to Scan Terraform Code
              run: |
                  checkov -d . --skip-check CKV2_AWS_5,CKV2_AWS_19,CKV2_AWS_12

            # Step 6: Terraform Init
            - name: Terraform Init
              run: terraform init

            # Step 7: Terraform Plan
            - name: Terraform Plan
              run: terraform plan

            # Step 8: Terraform Apply
            - name: Terraform Apply
              if: github.event_name == 'push'
              run: terraform apply -auto-approve
